[package]
name = "ingrid_core"
version = "1.3.1"
edition = "2021"
license = "MIT"
description = "Crossword-generating library and CLI tool"
repository = "https://github.com/rf-/ingrid_core"
readme = "README.md"

[dependencies]
smallvec = "1.8.0"
instant = { version = "0.1", features = ["wasm-bindgen"] }
lazy_static = "1.4.0"
float-ord = "0.3.2"
getrandom = { version = "0.2", features = ["js"] }
rand = { version = "0.8.5", features = ["std", "alloc",  "std_rng", "small_rng"] }
clap = { version = "4.0.15", features = ["derive"] }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
unicode-normalization = "0.1.22"
tempfile = "3"
fancy-regex = "0.14.0"
wasm-bindgen = { version = "0.2.100", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3.77", features = ["console", "Response", "Window", "Request"] }

[dev-dependencies]
ingrid_core = { path = ".", features = ["serde"] }
serde_json = "1.0.89"
indoc = "2.0.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wee_alloc = "0.4.5"
console_error_panic_hook = { version = "0.1.7", optional = true }

[features]
default = ["console_error_panic_hook"]
check_invariants = []
serde = ["dep:serde", "dep:serde_derive"]

[lib]
name = "ingrid_core"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "ingrid_core_bin"
path = "src/bin.rs"
